language: go

go:
    - 1.8
    - 1.9
    - tip

go_import_path: github.com/intel/govmm

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get github.com/mattn/goveralls

script:
   - if [[ -n "$(gofmt -l .)" ]]; then echo "The following files were not formatted properly!"; gofmt -l .; exit 1; fi
   - go env
   - $GOPATH/bin/goveralls -v -service=travis-ci
   - gometalinter --tests --vendor --disable-all --enable=misspell --enable=vet --enable=ineffassign --enable=gofmt --enable=gocyclo --cyclo-over=15 --enable=golint --enable=errcheck --enable=deadcode --enable=staticcheck -enable=gas ./...
